### ISSUE TITLE
Fix deployment config in `.travis.yml`

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/libnut-install#4]
Currently the deployment config on Travis is a bit misconfigured as it tries to publish on Windows and macOS as well.

The build config specifies a os filter for deployments:

```
deploy:
  - provider: script
    skip_cleanup: true
    script: npm publish --access public
    on:
      tags: true
      os: 'linux'
      node_js: '12'
```

It looks like the `os` specifier is not accepted / wrong, so we might have to use a [condition](https://docs.travis-ci.com/user/deployment-v2/conditional#examples-for-conditional-deployments) here.
