### ISSUE TITLE
Add node 13 and 14 to CI

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/libnut-install#5]
This ensures loading libnut on node 13 and 14 is possible.

Since the CI job is already a matrix build, 6 additional entries (2 version x 3 platforms) have to be added to the

```yaml
matrix:
  include:
    - os: linux
      dist: bionic
      node_js: "10"
    - os: osx
      osx_image: xcode11
      node_js: "10"
    - os: windows
      node_js: "10"
    ...
```

section in `.travis.yml`
